name: Build Installable Executables

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - feature/windows-standalone-build

jobs:
    build:
        strategy:
            fail-fast: false
        runs-on: "windows-2019"
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Cygwin
              uses: ./.github/actions/cygwin
              with:
                  platform: x64
                  packages: autoconf automake libtool wget zip zstd

            - name: Download and unpack pythonbuild repository
              shell: cmd
              run: |
                  wget https://github.com/indygreg/python-build-standalone/releases/download/20211017/cpython-3.9.7-x86_64-pc-windows-msvc-shared-install_only-20211017T1616.tar.gz
                  tar -zxvf cpython-3.9.7-x86_64-pc-windows-msvc-shared-install_only-20211017T1616.tar.gz

            - name: Cleanup pythonbuild repository
              shell: cmd
              run: |
                  rmdir /s /q python\tcl
                  rmdir /s /q python\Lib\turtledemo
                  rmdir /s /q python\Lib\tkinter
                  rmdir /s /q python\Lib\test
                  rmdir /s /q python\Lib\idlelib
                  rmdir /s /q python\Lib\distutils\tests
                  del /s *h

            - name: Ensure clean permissions
              shell: cmd
              run: yes | cacls python /t /g Everyone:f # fix the dll permissions

            - name: Copy installer script
              shell: cmd
              run: cp utility/venv_from_pip.py python/Scripts

            - name: Make zipfile
              shell: cmd
              run: zip -rm cci_installer.zip python

            - name: Add README
              shell: cmd
              run: echo "Run 'Scripts/python Scripts/venv_from_pip.py' to create a CumulusCI install environment" > "python/README.txt"

            - name: Upload executable
              uses: actions/upload-artifact@v2
              with:
                  name: cci_installer
                  if-no-files-found: error
                  path: cci_installer.zip
