name: Build Installable Executables

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - feature/windows-standalone-build

jobs:
    build:
        runs-on: "windows-2019"
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Cygwin
              uses: ./.github/actions/cygwin
              with:
                  platform: x64
                  packages: autoconf automake libtool wget zip zstd

            - name: Download and unpack pythonbuild repository
              shell: cmd
              run: |
                  wget https://github.com/indygreg/python-build-standalone/releases/download/20211017/cpython-3.9.7-x86_64-pc-windows-msvc-shared-install_only-20211017T1616.tar.gz
                  tar -zxvf cpython-3.9.7-x86_64-pc-windows-msvc-shared-install_only-20211017T1616.tar.gz

            - name: Rename Directory
              shell: pwsh
              run: move python cci_installer

            - name: Cleanup pythonbuild repository
              shell: cmd
              run: |
                  rmdir /s /q cci_installer\tcl
                  rmdir /s /q cci_installer\Lib\turtledemo
                  rmdir /s /q cci_installer\Lib\tkinter
                  rmdir /s /q cci_installer\Lib\test
                  rmdir /s /q cci_installer\Lib\idlelib
                  rmdir /s /q cci_installer\Lib\distutils\tests
                  del /s *.h

            - name: Ensure clean permissions
              shell: cmd
              run: yes | cacls cci_installer /t /g Everyone:f # fix the dll permissions

            - name: Copy installer script
              shell: cmd
              run: cp utility/venv_from_pip.py cci_installer/Scripts

            - name: Add static files
              shell: cmd
              run: |
                  echo "Run 'install.bat' to create a CumulusCI install environment" > cci_installer/README.txt
                  echo %%~dp0\python %%~dp0\Scripts\venv_from_pip.py > cci_installer/install.bat

            - name: Upload executable
              uses: actions/upload-artifact@v2
              with:
                  name: cci_installer.zip
                  if-no-files-found: error
                  path: cci_installer

    test:
        runs-on: "windows-2019"
        needs: build
        strategy:
            fail-fast: True
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: cci_installer.zip
                  path: cci_installer

            - name: See what's going on
              shell: cmd
              run: dir

            - name: See what's going on (2)
              shell: cmd
              run: dir cci_installer

            - name: See what's going on (3)
              shell: cmd
              run: dir cci_installer\install.bat

            - name: See what's going on (4)
              shell: cmd
              run: type cci_installer\install.bat

            - name: Install
              shell: cmd
              run: |
                  cci_installer\install.bat

            - name: Test installation
              shell: cmd
              run: |
                  %userprofile%\.cumulusci\pythonbin\Scripts\cci
